# cmake -P test/sparkle_feed_policy_test.cmake
# Exercises cmake/SpectrSparklePolicy.cmake: a release-numbered shipping app
# must read the release feed; practice/preview numbers and other identities may
# read any.
include(${CMAKE_CURRENT_LIST_DIR}/../cmake/SpectrSparklePolicy.cmake)

set(_failures 0)
function(expect label want_error kind build version feed channel)
    spectr_sparkle_feed_policy_error(_e "${kind}" "${build}" "${version}" "${feed}" "${channel}")
    if(want_error AND _e STREQUAL "")
        message("FAIL ${label}: expected a refusal, got none")
        math(EXPR _n "${_failures} + 1")
        set(_failures ${_n} PARENT_SCOPE)
    elseif(NOT want_error AND NOT _e STREQUAL "")
        message("FAIL ${label}: unexpected refusal: ${_e}")
        math(EXPR _n "${_failures} + 1")
        set(_failures ${_n} PARENT_SCOPE)
    else()
        message("PASS ${label}")
    endif()
endfunction()

set(_loop "http://127.0.0.1:8765/appcast-practice.xml")
expect("release build, release channel, no override" FALSE shipping "" 1.0.7 "" release)
expect("release build numbered explicitly"            FALSE shipping 1.0.7 1.0.7 "" release)
expect("release build with a feed override"           TRUE  shipping "" 1.0.7 "${_loop}" release)
expect("explicit release number with a feed override" TRUE  shipping 1.0.7 1.0.7 "https://x/a.xml" release)
expect("release build on the practice channel"        TRUE  shipping "" 1.0.7 "" practice)
expect("practice build with a loopback feed"          FALSE shipping 1.0.7.2 1.0.7 "${_loop}" practice)
expect("preview build with a feed override"           FALSE shipping 1.0.6.9001 1.0.7 "${_loop}" release)
expect("release build, updater off"                   FALSE shipping "" 1.0.7 "" off)
expect("preview identity with an override"            FALSE preview "" 1.0.7 "${_loop}" release)
expect("dev identity with an override"                FALSE dev "" 1.0.7 "${_loop}" release)

# Version regexes: a product version's dots are literal, so 1.0.7 must not
# accept 1x0y7 as itself.
spectr_sparkle_regex_escape(_re "1.0.7")
if(NOT "1.0.7" MATCHES "^${_re}$" OR "1x0y7" MATCHES "^${_re}$")
    message("FAIL the escaped version regex matches only its own literal (got ${_re})")
    math(EXPR _failures "${_failures} + 1")
else()
    message("PASS the escaped version regex matches only its own literal")
endif()
# Preview prefixes, mirroring tools/check_release_version.py preview_prefix.
foreach(_case "1;0;7;1.0.6" "1;1;0;1.0.9999" "2;0;0;1.9999.9999" "0;0;0;")
    list(GET _case 0 _x)
    list(GET _case 1 _y)
    list(GET _case 2 _z)
    list(LENGTH _case _n)
    set(_want "")
    if(_n GREATER 3)
        list(GET _case 3 _want)
    endif()
    spectr_sparkle_preview_prefix(_got ${_x} ${_y} ${_z})
    if(NOT _got STREQUAL _want)
        message("FAIL preview prefix of ${_x}.${_y}.${_z}: got '${_got}', want '${_want}'")
        math(EXPR _failures "${_failures} + 1")
    else()
        message("PASS preview prefix of ${_x}.${_y}.${_z} is '${_got}'")
    endif()
endforeach()

if(_failures GREATER 0)
    message(FATAL_ERROR "${_failures} sparkle feed policy case(s) failed")
endif()
