// Generated by Pulp import-design from Claude Design
// Source: editor.html

if (typeof motion !== 'undefined' && motion.setProvenance)
    motion.setProvenance('design-import', 'claude:Browser-evaluated HTML');

setTheme('dark');

if (typeof setSubpixelLayout === 'function') setSubpixelLayout('', true);

// Design tokens
setColorToken('css/warm', 'oklch(0.80 0.16 60)');
setColorToken('css/violet', 'oklch(0.70 0.18 290)');
setColorToken('css/panel-border', 'rgba(255,255,255,0.08)');
setColorToken('css/hair-2', 'rgba(232,237,242,0.12)');
setColorToken('css/hair', 'rgba(232,237,242,0.06)');
setColorToken('css/panel', 'rgba(12,16,22,0.92)');
setColorToken('css/ink', '#e8edf2');
setColorToken('css/grid', 'rgba(255,255,255,0.06)');
setColorToken('css/green', 'oklch(0.78 0.14 150)');
setColorToken('css/glow-1', 'rgba(40,90,140,0.08)');
setColorToken('css/danger', 'oklch(0.68 0.19 25)');
setColorToken('css/cool', 'oklch(0.78 0.14 220)');
setColorToken('css/chip-border-active', 'rgba(180,210,255,0.4)');
setColorToken('css/bg', '#05070a');
setColorToken('css/grid-strong', 'rgba(255,255,255,0.14)');
setColorToken('css/chip-bg-active', 'rgba(120,180,255,0.14)');
setColorToken('css/glow-2', 'rgba(140,40,120,0.05)');
setColorToken('css/dim', '#6b7380');
setColorToken('css/chip-bg', 'rgba(255,255,255,0.03)');
setColorToken('css/chip-border', 'rgba(255,255,255,0.1)');
setColorToken('css/accent', 'oklch(0.78 0.14 220)');

// @pulp-anchor browser:root
createCol('root', '');
setOverflow('root', 'hidden');
setFlex('root', 'height', 860);
setFlex('root', 'width', 1320);

  // @pulp-anchor browser:paint-authority
  // Accepted Chromium chrome
  createImage('Accepted_Chromium_chrome0', 'root');
  setPosition('Accepted_Chromium_chrome0', 'absolute');
  setLeft('Accepted_Chromium_chrome0', 0);
  setTop('Accepted_Chromium_chrome0', 0);
  setObjectFit('Accepted_Chromium_chrome0', 'fill');
  setImageSource('Accepted_Chromium_chrome0', 'assets/25ee97e9130cc8e719e4514a227dca176877a5ec0aaaf5cb2f5125b369386249.png');
  setFlex('Accepted_Chromium_chrome0', 'width', 1320);
  setFlex('Accepted_Chromium_chrome0', 'height', 860);

  setAnchor('Accepted_Chromium_chrome0', 'browser:paint-authority');
  // @pulp-anchor browser:canvas:0
  createCanvas('Browser_canvas_11', 'root');
  setPosition('Browser_canvas_11', 'absolute');
  setLeft('Browser_canvas_11', 0);
  setTop('Browser_canvas_11', 0);
  setFlex('Browser_canvas_11', 'width', 1320);
  setFlex('Browser_canvas_11', 'height', 860);

  setAnchor('Browser_canvas_11', 'browser:canvas:0');
  // @pulp-anchor browser:canvas:1
  createCanvas('Browser_canvas_22', 'root');
  setPosition('Browser_canvas_22', 'absolute');
  setLeft('Browser_canvas_22', 0);
  setTop('Browser_canvas_22', 0);
  setFlex('Browser_canvas_22', 'width', 1320);
  setFlex('Browser_canvas_22', 'height', 860);

  setAnchor('Browser_canvas_22', 'browser:canvas:1');
setAnchor('root', 'browser:root');
void 0;
