#!/usr/bin/env python3
"""Reuse Settings modulation state in a compact, persistently mounted menu panel."""
import json
from pathlib import Path

PATH = Path(__file__).resolve().parents[1] / 'native-ui/materialized/materialized-document.runtime.json'
MARKER = 'const __spectrSharedModulationMenu = true;'
STACK_MARKER = 'const __spectrBandMenuGlobalLayer = true;'

def once(source, before, after):
    assert source.count(before) == 1, repr(before[:100])
    return source.replace(before, after, 1)

def make_adjacent_modulation_submenu(html):
    if 'data-spectr-modulation-anchor' in html:
        assert html.count('data-spectr-modulation-anchor') == 1
        assert html.count('sub: "›"') == 1
        # This script is intentionally re-runnable.  A runtime generated by
        # an earlier version already has the submenu body, so only fill in
        # the later viewport/scroll refinements here.
        if 'maxHeight: menuMaxHeight' not in html:
            html = once(html, '  const H = 420 + (hasBand ? 100 : 0) + (hasSel ? 160 : 0) + assigned.length * 26;\n',
                        '  const estimatedHeight = 420 + (hasBand ? 100 : 0) + (hasSel ? 160 : 0) + assigned.length * 26;\n'
                        '  const menuMaxHeight = Math.max(180, vh - 16);\n'
                        '  const H = Math.min(estimatedHeight, menuMaxHeight);\n')
            html = once(html, '        zIndex: 81,\n        pointerEvents: "auto"',
                        '        zIndex: 2147483001,\n        maxHeight: menuMaxHeight, overflowY: "auto",\n'
                        '        overscrollBehavior: "contain", pointerEvents: "auto"')
            html = once(html, '          backdropFilter: "blur(12px)", zIndex: 1, pointerEvents: "auto"',
                        '          backdropFilter: "blur(12px)", zIndex: 2147483002,\n'
                        '          maxHeight: menuMaxHeight, overflowY: "auto",\n'
                        '          overscrollBehavior: "contain", pointerEvents: "auto"')
        return html

    start = html.index('function ContextMenu(')
    end = html.index('window.ContextMenu', start)
    menu = html[start:end]
    menu = once(
        menu,
        '  const [modulationOpen, setModulationOpen] = React.useState(false);',
        '''  const [modulationOpen, setModulationOpen] = React.useState(false);
  const [modulationSource, setModulationSource] = React.useState(1);
  const spectrModulationShapes = ["Sin", "Tri", "Square", "Saw"];
  const spectrModulationRates = [0.25, 0.5, 1, 2, 4, 8, 16];
  const spectrModulationDepths = [0, 0.25, 0.5, 0.75, 1];
  const spectrCycleModulationValue = (values, current) => {
    const index = values.findIndex(value => Math.abs(value - current) < 1e-6);
    return values[(index + 1 + values.length) % values.length];
  };''')
    menu = once(
        menu,
        '  const H = 420 + (hasBand ? 100 : 0) + (hasSel ? 160 : 0) + assigned.length * 26;\n',
        '  const estimatedHeight = 420 + (hasBand ? 100 : 0) + (hasSel ? 160 : 0) + assigned.length * 26;\n'
        '  const menuMaxHeight = Math.max(180, vh - 16);\n'
        '  const H = Math.min(estimatedHeight, menuMaxHeight);\n')
    menu = once(
        menu,
        '  const left = Math.max(8, Math.min(x, vw - W - 8));\n'
        '  const top = Math.max(8, Math.min(y, vh - H - 8));',
        '  const left = Math.max(8, Math.min(x, vw - W - 8));\n'
        '  const top = Math.max(8, Math.min(y, vh - H - 8));\n'
        '  const submenuOnLeft = left + W * 2 + 6 > vw - 8;')
    menu = once(
        menu,
        '  const Item = ({ action, label, hint, onClick, disabled, danger, sub, keepOpen, checked })',
        '  const Item = ({ action, label, hint, onClick, onKeyDown, onHover, disabled, danger, sub, keepOpen, checked, expanded, hasPopup })')
    menu = once(
        menu,
        '      "aria-checked": checked,\n      "data-spectr-band-action": action,',
        '      "aria-checked": checked,\n'
        '      "aria-expanded": expanded,\n'
        '      "aria-haspopup": hasPopup,\n'
        '      "data-spectr-band-action": action,\n'
        '      onKeyDown,')
    menu = once(
        menu,
        '      onMouseEnter: (e) => {\n'
        '        if (!disabled) e.currentTarget.style.background = "rgba(120,180,255,0.14)";\n'
        '      },',
        '      onMouseEnter: (e) => {\n'
        '        if (!disabled) {\n'
        '          e.currentTarget.style.background = "rgba(120,180,255,0.14)";\n'
        '          if (onHover) onHover();\n'
        '        }\n'
        '      },')
    menu = once(
        menu,
        '      onDismiss: onClose,\n      style: {',
        '      onDismiss: onClose,\n'
        '      onKeyDown: (event) => {\n'
        '        if (modulationOpen && event.key === "ArrowLeft") {\n'
        '          event.preventDefault();\n'
        '          setModulationOpen(false);\n'
        '        }\n'
        '      },\n'
        '      style: {')
    menu = once(
        menu,
        '    React.createElement("div", { "data-spectr-main-menu-panel": true, style: { display: modulationOpen ? "none" : "flex", flexDirection: "column" } },',
        '    React.createElement("div", { "data-spectr-main-menu-panel": true, style: { display: "flex", flexDirection: "column" } },')
    old_toggle = '    React.createElement(Item, { action: "modulation-toggle", label: "Modulation", sub: ">", keepOpen: true, onClick: () => setModulationOpen(true) }),'
    new_toggle = '''    React.createElement("div", {
      "data-spectr-modulation-anchor": true,
      style: { position: "relative", width: "100%" }
    },
      React.createElement(Item, {
        action: "modulation-toggle", label: "Modulation", sub: "›",
        keepOpen: true, expanded: modulationOpen, hasPopup: "menu",
        onHover: () => setModulationOpen(true),
        onKeyDown: (event) => {
          if (event.key === "ArrowRight") {
            event.preventDefault();
            setModulationOpen(true);
          }
        },
        onClick: () => setModulationOpen(open => !open)
      }),
      modulationOpen && React.createElement("div", {
        "data-spectr-modulation-panel": true,
        role: "menu",
        "aria-label": "Modulation",
        style: {
          display: "flex", flexDirection: "column", position: "absolute",
          left: submenuOnLeft ? -(W + 6) : W + 6, top: 0, width: W,
          background: "rgba(12,16,22,0.97)",
          border: "1px solid rgba(255,255,255,0.12)", borderRadius: 5,
          padding: "6px 0", boxShadow: "0 14px 40px rgba(0,0,0,0.6)",
          backdropFilter: "blur(12px)", zIndex: 2147483002,
          maxHeight: menuMaxHeight, overflowY: "auto",
          overscrollBehavior: "contain", pointerEvents: "auto"
        }
      },
        React.createElement(Item, { action: "modulation-back", label: "‹ Back", keepOpen: true, onClick: () => setModulationOpen(false) }),
        React.createElement(Divider, { label: "MODULATION" }),
        React.createElement(Item, { action: "lfo1-enable", label: "LFO 1", sub: modulation.enabled ? "On" : "Off", checked: modulation.enabled, disabled: !modulationReady, keepOpen: true, onClick: () => publishModulation("enabled", 4000, !modulation.enabled) }),
        React.createElement(Item, { action: "lfo2-enable", label: "LFO 2", sub: modulation.lfo2Enabled ? "On" : "Off", checked: modulation.lfo2Enabled, disabled: !modulationReady, keepOpen: true, onClick: () => publishModulation("lfo2Enabled", 4010, !modulation.lfo2Enabled) }),
        React.createElement("div", { "data-spectr-modulation-source": modulationSource, style: { display: "flex", gap: 5, padding: "5px 10px" } },
          [1, 2].map(source => React.createElement("button", {
            key: source, type: "button", "data-spectr-modulation-source-action": source,
            "aria-pressed": modulationSource === source,
            onClick: () => setModulationSource(source),
            style: {
              flex: 1, padding: "5px 7px", borderRadius: 3,
              border: "1px solid " + (modulationSource === source ? "rgba(180,210,255,0.4)" : "rgba(255,255,255,0.1)"),
              background: modulationSource === source ? "rgba(120,180,255,0.18)" : "rgba(255,255,255,0.03)",
              color: modulationSource === source ? "#fff" : "rgba(255,255,255,0.7)",
              fontFamily: "var(--mono)", fontSize: 9.5, cursor: "pointer"
            }
          }, "EDIT LFO " + source))
        ),
        React.createElement(Divider, { label: "LFO " + modulationSource + " PARAMETERS" }),
        React.createElement(Item, {
          action: modulationSource === 1 ? "lfo1-shape" : "lfo2-shape", label: "Shape", keepOpen: true,
          sub: spectrModulationShapes[modulationSource === 1 ? modulation.shape : modulation.lfo2Shape],
          disabled: !modulationReady,
          onClick: () => {
            const key = modulationSource === 1 ? "shape" : "lfo2Shape";
            publishModulation(key, modulationSource === 1 ? 4001 : 4011,
              spectrCycleModulationValue([0, 1, 2, 3], modulation[key]));
          }
        }),
        React.createElement(Item, {
          action: modulationSource === 1 ? "lfo1-rate" : "lfo2-rate", label: "Rate", keepOpen: true,
          sub: (modulationSource === 1 ? modulation.rate : modulation.lfo2Rate) + " beats",
          disabled: !modulationReady,
          onClick: () => {
            const key = modulationSource === 1 ? "rate" : "lfo2Rate";
            publishModulation(key, modulationSource === 1 ? 4002 : 4012,
              spectrCycleModulationValue(spectrModulationRates, modulation[key]));
          }
        }),
        React.createElement(Item, {
          action: modulationSource === 1 ? "lfo1-depth" : "lfo2-depth", label: "Depth", keepOpen: true,
          sub: Math.round((modulationSource === 1 ? modulation.depth : modulation.lfo2Depth) * 100) + "%",
          disabled: !modulationReady,
          onClick: () => {
            const key = modulationSource === 1 ? "depth" : "lfo2Depth";
            publishModulation(key, modulationSource === 1 ? 4003 : 4013,
              spectrCycleModulationValue(spectrModulationDepths, modulation[key]));
          }
        }),
        React.createElement(Divider, { label: "SHARED TARGET" }),
        [[0, "bank", "Bank"], [1, "a", "Snapshot A"], [2, "b", "Snapshot B"], [3, "morph", "Morph"]].map(([target, key, label]) => React.createElement(Item, {
          key, action: "modulation-target-" + key, label,
          checked: modulation.targetMask === (1 << target),
          sub: modulation.targetMask === (1 << target) ? "Active" : undefined,
          disabled: !modulationReady,
          keepOpen: true,
          onClick: () => publishModulation("target", 4004, target)
        }))
      )
    ),'''
    menu = once(menu, old_toggle, new_toggle)
    old_panel = '''    React.createElement("div", { "data-spectr-modulation-panel": true, style: { display: modulationOpen ? "flex" : "none", flexDirection: "column" } },
      React.createElement(Item, { action: "modulation-back", label: "< Back", keepOpen: true, onClick: () => setModulationOpen(false) }),
      React.createElement(Divider, { label: "MODULATION" }),
      React.createElement(Item, { action: "lfo1-enable", label: "LFO 1", sub: modulation.enabled ? "On" : "Off", checked: modulation.enabled, disabled: !modulationReady, keepOpen: true, onClick: () => publishModulation("enabled", 4000, !modulation.enabled) }),
      React.createElement(Item, { action: "lfo2-enable", label: "LFO 2", sub: modulation.lfo2Enabled ? "On" : "Off", checked: modulation.lfo2Enabled, disabled: !modulationReady, keepOpen: true, onClick: () => publishModulation("lfo2Enabled", 4010, !modulation.lfo2Enabled) }),
      React.createElement(Divider, { label: "SHARED TARGET" }),
      [[0, "bank", "Bank"], [1, "a", "Snapshot A"], [2, "b", "Snapshot B"], [3, "morph", "Morph"]].map(([target, key, label]) => React.createElement(Item, {
        key, action: "modulation-target-" + key, label,
        checked: modulation.targetMask === (1 << target),
        sub: modulation.targetMask === (1 << target) ? "Active" : undefined,
        disabled: !modulationReady,
        onClick: () => publishModulation("target", 4004, target)
      }))
    )
'''
    menu = once(menu, old_panel, '')
    return html[:start] + menu + html[end:]

def add_global_menu_layer(html):
    html = make_adjacent_modulation_submenu(html)
    if STACK_MARKER in html:
        assert html.count(STACK_MARKER) == 1
        assert html.count('spectrBandMenuPortal(/* @__PURE__ */ React.createElement(') == 1
        assert html.count('style: spectrBandMenuLayerStyle()') == 1
        return html

    filter_start = html.index('function FilterBank(')
    filter_end = html.index('\nconst StableContextMenu', filter_start)
    filter_bank = html[filter_start:filter_end]
    helpers = '''const __spectrBandMenuGlobalLayer = true;
function spectrBandMenuPortal(menu) {
  const layer = document.querySelector("[data-spectr-global-menu-layer]");
  // The layer is mounted by App before a user can open a context menu.  Keep
  // a graceful inline fallback for headless first-commit probes and hot reload.
  return layer ? ReactDOM.createPortal(menu, layer) : menu;
}
function spectrBandMenuLayerStyle() {
  return {
    position: "absolute", inset: 0, zIndex: 2147483000,
    overflow: "visible", pointerEvents: "none"
  };
}
'''
    html = html[:filter_start] + helpers + html[filter_start:]

    # Render the menu into a last-child root overlay. A high z-index on the
    # menu alone cannot escape FilterBank's native subtree: Chrome and the
    # universal status banner are later root siblings and therefore paint over
    # nested children even when those children claim a larger local z-index.
    filter_start = html.index('function FilterBank(')
    filter_end = html.index('\nconst StableContextMenu', filter_start)
    filter_bank = html[filter_start:filter_end]
    filter_bank = once(
        filter_bank,
        '    ctxMenu && /* @__PURE__ */ React.createElement(\n      StableContextMenu,',
        '    ctxMenu && spectrBandMenuPortal(/* @__PURE__ */ React.createElement(\n      StableContextMenu,')
    close = filter_bank.rfind('\n    )\n  );\n}')
    assert close >= 0, 'FilterBank context-menu close not found'
    filter_bank = filter_bank[:close] + filter_bank[close:].replace(
        '\n    )\n  );\n}', '\n    ))\n  );\n}', 1)
    html = html[:filter_start] + filter_bank + html[filter_end:]

    context_start = html.index('function ContextMenu(')
    context_end = html.index('window.ContextMenu', context_start)
    context = html[context_start:context_end]
    context = once(
        context,
        '        zIndex: 40,',
        '        zIndex: 2147483001,\n'
        '        maxHeight: menuMaxHeight,\n'
        '        overflowY: "auto",\n'
        '        overscrollBehavior: "contain",')
    html = html[:context_start] + context + html[context_end:]

    app_start = html.index('function App()')
    app_end = html.index('\nReactDOM.createRoot(', app_start)
    app = html[app_start:app_end]
    close = app.rfind('\n  ));\n}')
    assert close >= 0, 'App root close not found'
    app = app[:close] + app[close:].replace(
        '\n  ));\n}',
        '\n  ), /* @__PURE__ */ React.createElement("div", {\n'
        '    "data-spectr-global-menu-layer": true,\n'
        '    style: spectrBandMenuLayerStyle()\n'
        '  }));\n}', 1)
    return html[:app_start] + app + html[app_end:]

def transform(html):
    if MARKER in html:
        assert html.count(MARKER) == 1
        assert html.count('window.useSpectrModulationState = useSpectrModulationState;') == 1
        assert 'data-spectr-modulation-panel' in html
        return add_global_menu_layer(html)
    start = html.index('function SpectrModulationSettings() {')
    end = html.index('  return /* @__PURE__ */ React.createElement("div", { "data-spectr-settings-tabs"', start)
    original = html[start:end]
    hook = once(original, 'function SpectrModulationSettings() {',
                'function useSpectrModulationState() {\n  const [ready, setReady] = React.useState(false);')
    hook = once(hook, '    if (!modulation || typeof modulation !== "object") return;',
                '    if (!modulation || typeof modulation !== "object") return;\n    setReady(true);')
    hook += '''  return { value, ready, publish, publishTargetMask, publishMorphViewport, publishTargets };
}
window.useSpectrModulationState = useSpectrModulationState;
function SpectrModulationSettings() {
  const { value, publish, publishTargetMask, publishMorphViewport, publishTargets } = useSpectrModulationState();
'''
    html = once(html, original, hook)
    start = html.index('function ContextMenu(')
    end = html.index('window.ContextMenu', start)
    original = html[start:end]
    menu = original
    brace = menu.index(') {') + len(') {')
    menu = menu[:brace] + '''
  const __spectrSharedModulationMenu = true;
  const [modulationOpen, setModulationOpen] = React.useState(false);
  const { value: modulation, ready: modulationReady, publish: publishModulation } = window.useSpectrModulationState();
''' + menu[brace:]
    modes_start = menu.index('  const modes = [')
    modes_end = menu.index('  const Item =', modes_start)
    menu = menu[:modes_start] + menu[modes_end:]
    menu = once(menu, 'danger, sub })', 'danger, sub, keepOpen, checked })')
    menu = once(menu, '      role: "menuitem",',
                '      role: checked === undefined ? "menuitem" : "menuitemcheckbox",\n      "aria-checked": checked,')
    menu = once(menu, '          onClose();', '          if (!keepOpen) onClose();')
    menu = once(menu, 'hint: "⌘Z"', 'hint: "Cmd+Z"')
    menu = once(menu, 'hint: "⌘⇧Z"', 'hint: "Cmd+Shift+Z"')
    # Keep both panels mounted: late-mounting rows append in the native bridge.
    first = '    hasBand && /* @__PURE__ */ React.createElement(React.Fragment'
    menu = once(menu, first, '''    React.createElement("div", { "data-spectr-main-menu-panel": true, style: { display: modulationOpen ? "none" : "flex", flexDirection: "column" } },
''' + first)
    view = '    /* @__PURE__ */ React.createElement(Divider, { label: "VIEW" }),'
    menu = once(menu, view, '''    React.createElement(Item, { action: "modulation-toggle", label: "Modulation", sub: ">", keepOpen: true, onClick: () => setModulationOpen(true) }),
''' + view)
    tail = '''    }))
  );
}'''
    replacement = '''    }))),
    React.createElement("div", { "data-spectr-modulation-panel": true, style: { display: modulationOpen ? "flex" : "none", flexDirection: "column" } },
      React.createElement(Item, { action: "modulation-back", label: "< Back", keepOpen: true, onClick: () => setModulationOpen(false) }),
      React.createElement(Divider, { label: "MODULATION" }),
      React.createElement(Item, { action: "lfo1-enable", label: "LFO 1", sub: modulation.enabled ? "On" : "Off", checked: modulation.enabled, disabled: !modulationReady, keepOpen: true, onClick: () => publishModulation("enabled", 4000, !modulation.enabled) }),
      React.createElement(Item, { action: "lfo2-enable", label: "LFO 2", sub: modulation.lfo2Enabled ? "On" : "Off", checked: modulation.lfo2Enabled, disabled: !modulationReady, keepOpen: true, onClick: () => publishModulation("lfo2Enabled", 4010, !modulation.lfo2Enabled) }),
      React.createElement(Divider, { label: "SHARED TARGET" }),
      [[0, "bank", "Bank"], [1, "a", "Snapshot A"], [2, "b", "Snapshot B"], [3, "morph", "Morph"]].map(([target, key, label]) => React.createElement(Item, {
        key, action: "modulation-target-" + key, label,
        checked: modulation.targetMask === (1 << target),
        sub: modulation.targetMask === (1 << target) ? "Active" : undefined,
        disabled: !modulationReady,
        onClick: () => publishModulation("target", 4004, target)
      }))
    )
  );
}'''
    menu = once(menu, tail, replacement)
    return add_global_menu_layer(once(html, original, menu))

def main():
    document = json.loads(PATH.read_text())
    updated = transform(document['html'])
    if updated == document['html']:
        print('Shared modulation menu already applied')
        return
    document['html'] = updated
    PATH.write_text(json.dumps(document, separators=(',', ':'), ensure_ascii=False) + '\n')
    print('Added shared modulation state and compact menu panel')

if __name__ == '__main__':
    main()
